import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import Navauth from "./components/Navauth";
import FooterAuth from "./components/FooterAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full`}
      >
        <Navauth />
        {children}
        <FooterAuth />
      </body>
    </html>
  );
}
